name: luxy_flutter_code
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'  # Flutter 2.0 and onwards use Dart 2.12.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.0
  device_preview: ^1.1.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/LuxY.png  # Add the path to your image file here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0