// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzSRXRigjKLuKCiKDZ2dODO47ye9PD3U',
    appId: '1:89655157327:web:72a85d5a14670b543b803a',
    messagingSenderId: '89655157327',
    projectId: 'luxy-tcc',
    authDomain: 'luxy-tcc.firebaseapp.com',
    storageBucket: 'luxy-tcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYep9He5V8i5Oa3SVas1xF_OXkB11XQ6w',
    appId: '1:89655157327:android:db8d08e16e3451f23b803a',
    messagingSenderId: '89655157327',
    projectId: 'luxy-tcc',
    storageBucket: 'luxy-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJafsPRvpctuHBqWqo96Lgg3vlEToZZU',
    appId: '1:89655157327:ios:a4941047b1d1d1863b803a',
    messagingSenderId: '89655157327',
    projectId: 'luxy-tcc',
    storageBucket: 'luxy-tcc.appspot.com',
    iosBundleId: 'com.example.luxyFlutterCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJafsPRvpctuHBqWqo96Lgg3vlEToZZU',
    appId: '1:89655157327:ios:a93ed9ef93fca8ca3b803a',
    messagingSenderId: '89655157327',
    projectId: 'luxy-tcc',
    storageBucket: 'luxy-tcc.appspot.com',
    iosBundleId: 'com.example.luxyFlutterCode.RunnerTests',
  );
}
